package com.roloduck.entity;

import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.core.RowMapper;

/**
 * @author Andrew Ertell
 * @author Peter Johnston
 * @since 3/6/14
 * RoloDuck
 */

public interface RoloDuckEntity {
    /**
     * Retrieve the name of the table related to the entity
     * @return the name of the table
     */
    public String getTableName();

    /**
     * Get an array of column names in the table related to the entity.
     * Note: This array does not include columns that are auto generated by the database such as id, or date_added
     * @return the array of column names
     */
    public String[] getDistinctColumnNames();

    /**
     * Get an array of all column names pertaining to the entity from its table
     * Note: This includes auto generated columns and all foreign keys
     * @return the array of all column names
     */
    public String[] getAllColumnNames();
    /**
     * Return the applicable PreparedStatementCreator to be used in the JDBCTemplate update method
     * @param SQL the SQL string to be run
     * @return the PreparedStatementCreator implementation
     */
    public PreparedStatementCreator getPreparedStatementCreator(final String SQL);

    /**
     * Return the entity's version of a RowMapper
     * @return The entity's specific RowMapper impl
     */
    public RowMapper getEntityMapper();

    /**
     * @return the entity's id
     */
    public long getId();

    /**
     * Set the entity's id
     * @param id the id given to the entity
     */
    public void setId(long id);
}
